dz_order_submit_process_list : 
  path: /dz/order_submit_processes
  methods: [GET]
  defaults:
    _controller: 'Dolzay\Apps\OrderSubmitProcess\Controllers\OrderSubmitProcessController::orderSubmitProcessList'
    _disable_module_prefix: true


dz_is_there_a_process_running : 
  path : /dz/is_there_a_process_running 
  methods : [GET]
  defaults : 
    _controller: 'Dolzay\Apps\OrderSubmitProcess\Controllers\OrderSubmitProcessController::isThereAProcessRunning'
    _disable_module_prefix: true

dz_order_submit_process_detail : 
  path: /dz/order_submit_process/{process_id}/
  methods: [GET]
  requirements:
    process_id: \d+
  defaults:
    _controller: 'Dolzay\Apps\OrderSubmitProcess\Controllers\OrderSubmitProcessController::orderSubmitProcessDetail'
    _disable_module_prefix: true

dz_launch_order_submit_process:
  path: /dz/order_submit_process
  methods: [POST]
  defaults:
    _controller: 'Dolzay\Apps\OrderSubmitProcess\Controllers\OrderSubmitProcessController::launchOrderSubmitProcess'
    _disable_module_prefix: true


dz_continue_order_submit_process:
  path: /dz/order_submit_process/{process_id}/continue
  methods: [PUT]
  requirements:
    process_id: \d+
  defaults:
    _controller: 'Dolzay\Apps\OrderSubmitProcess\Controllers\OrderSubmitProcessController::continueOrderSubmitProcess'
    _disable_module_prefix: true

dz_cancel_order_submit_process:
  path: /dz/order_submit_process/{process_id}/cancel
  methods: [PUT]
  requirements:
    process_id: \d+
  defaults:
    _controller: 'Dolzay\Apps\OrderSubmitProcess\Controllers\OrderSubmitProcessController::cancelOrderSubmitProcess'
    _disable_module_prefix: true

dz_terminate_order_submit_process:
  path: /dz/order_submit_process/{process_id}/terminate
  methods: [PUT]
  requirements:
    process_id: \d+
  defaults:
    _controller: 'Dolzay\Apps\OrderSubmitProcess\Controllers\OrderSubmitProcessController::terminateOrderSubmitProcess'
    _disable_module_prefix: true

dz_monitor_order_submit_process:
  path: /dz/order_submit_process/{process_id}/monitor
  methods: [GET]
  requirements:
    process_id: \d+
  defaults:
    _controller: 'Dolzay\Apps\OrderSubmitProcess\Controllers\OrderSubmitProcessController::monitorOrderSubmitProcess'
    _disable_module_prefix: true

