dz_launch_order_monitoring_process:
  path: /dz/order_monitoring_process
  methods: [POST]
  defaults:
    _controller: 'Dolzay\Apps\OrderMonitoringProcess\Controllers\OrderMonitoringProcessController::launchOrderMonitoringProcess'
    _disable_module_prefix: true

dz_monitor_order_monitoring_process:
  path: /dz/order_monitoring_process/{process_id}/monitor
  methods: [GET]
  requirements:
    process_id: \d+
  defaults:
    _controller: 'Dolzay\Apps\OrderMonitoringProcess\Controllers\OrderMonitoringProcessController::monitorOrderMonitoringProcess'
    _disable_module_prefix: true

dz_order_monitoring_process_list : 
  path: /dz/order_monitoring_processes
  methods: [GET]
  defaults:
    _controller: 'Dolzay\Apps\OrderMonitoringProcess\Controllers\OrderMonitoringProcessController::orderMonitoringProcessList'
    _disable_module_prefix: true

dz_order_monitoring_submit_process_detail : 
  path: /dz/order_monitoring_process/{process_id}/
  methods: [GET]
  requirements:
    process_id: \d+
  defaults:
    _controller: 'Dolzay\Apps\OrderMonitoringProcess\Controllers\OrderMonitoringProcessController::orderMonitoringProcessDetail'
    _disable_module_prefix: true

dz_get_updated_orders_of_an_osp : 
  path: /dz/order_monitoring_process/{process_id}/updated_orders/
  methods: [GET]
  requirements:
    process_id: \d+
  defaults:
    _controller: 'Dolzay\Apps\OrderMonitoringProcess\Controllers\OrderMonitoringProcessController::getUpdatedOrdersOfAnOsp'
    _disable_module_prefix: true

dz_get_orders_with_errors_of_an_osp : 
  path: /dz/order_monitoring_process/{process_id}/orders_with_errors/
  methods: [GET]
  requirements:
    process_id: \d+
  defaults:
    _controller: 'Dolzay\Apps\OrderMonitoringProcess\Controllers\OrderMonitoringProcessController::getOrdersWithErrorsOfAnOsp'
    _disable_module_prefix: true