

notifications_routes:
    resource: '../src/Apps/Notifications/routes.yaml'

order_submit_process_routes:
    resource: '../src/Apps/OrderSubmitProcess/routes.yaml'

order_monitoring_process_routes:
    resource: '../src/Apps/OrderMonitoringProcess/routes.yaml'

settings_routes : 
    resource: '../src/Apps/Settings/routes.yaml'




